### ISSUE TITLE
Are there any Types (d.ts)?

### ISSUE THREAD

**Issue by itayronen** [ElasticEmail/ElasticEmail.WebApiClient-js#3]
Hi,
My startup is considering to use your service.
We are using typescript and it would be amazing if you had types.

You do have a lot of comment docs, but its still confusing.
For example:
On Logs.Load(), the status param doc is:
 * @param {Object} data.statuses - List of comma separated message statuses: 0 for all, 1 for ReadyToSend, 2 for InProgress, 4 for Bounced, 5 for Sent, 6 for Opened, 7 for Clicked, 8 for Unsubscribed, 9 for Abuse Report.

So what is it? It says its an {Object}, and a list, and what does a list mean? A javascript array or a string of comma seperated numbers?

Thanks,
Itay

**Comment by ppodolak** [comment]
@itayronen Hi,
yes we are planing to create proper types for our library, for now i suggest using
`// @ts-ignore` above import of the package. Thanks for pointing out inconsistency in the docs. The param that you are asking should be string with comma separated enums, like `"2,4,5"`, we will try to cover this asap, in the meantime i suggest using docs from our [site](urlhttps://api.elasticemail.com/public/help).

**Comment by itayronen** [comment]
Thank you for the quick response :)
It is very important for us.
One of the reasons that we wanted to give ElasticEmail a try was the fact that this repository seemed alive unlike many of the alternatives.

I got email sending down and wrote it in typescript. Maybe I'll end up uploading a package for basic usage written in typescript.

I'll close the issue for now.
