### ISSUE TITLE
How to create a non-scheduled campaign from the API

### ISSUE THREAD

**Issue by michaelrambeau** [ElasticEmail/ElasticEmail.WebApiClient-js#4]
Hello,
First, thank you for your service that I use to send a newsletter about JavaScript trends: https://weekly.bestofjs.org/.
I try to create a campaign using the `campaign/add` end point from the API.

A parameter named `campaign` is expected. When I use the following value:

```js
{
  name: 'My campaign',
  targets: [l123],
  CampaignTemplates: [
    {
      TemplateID: '5213',
      TemplateSubject: 'My subject',
      TemplateFromEmail: 'hello@bestofjs.org',
      TemplateReplyEmail: 'hello@bestofjs.org',
      TemplateReplyName: 'Best of JavaScript'
    }
  ],
  TriggerType: 1 // 1 means "SendNow"
}
```

...I get the following error:

```
Trigger count and trigger frequency can only be set for scheduled campaigns
```

But I don't pass any "trigger" parameter and I don't want a scheduled newsletter, I want to send it manually later.

Am I missing something? How can I unset the "trigger" parameters?
Thank you very much for your help!

**Comment by ppodolak** [comment]
@michaelrambeau Hi,
It's good to hear you found our service useful 👍. Sorry for late answer but we had to adjust our api for better coverage of your problem. Now you can just set `CampaignStatus` as  `Draft`,  then you can just set manualy on demand to `Active`.

**Comment by michaelrambeau** [comment]
Hello @ppodolak 
Thank you for your answer.
Setting the `CampaignStatus` to `Draft` worked, no error, but the campaign that was created was not a "Draft", it was a "Regular" one and its status was **"Sending"**.

![image](https://user-images.githubusercontent.com/5546996/42185994-e07fe54e-7e85-11e8-9a54-adc7cf606284.png)

Is it the expected behavior?
Thank you again for your help!

**Comment by ppodolak** [comment]
@michaelrambeau I will look into it, could show the params you are setting for this request?

**Comment by michaelrambeau** [comment]
@ppodolak Here is the `campaign` parameter (the same as before, plus `CampaignStatus`):

```js
{
  name: 'My campaign',
  targets: ['l528'],
  CampaignTemplates: [
    {
      TemplateID: '5213',
      TemplateSubject: 'My subject',
      TemplateFromEmail: 'hello@bestofjs.org',
      TemplateReplyEmail: 'hello@bestofjs.org',
      TemplateReplyName: 'Best of JavaScript'
    }
  ],
  TriggerType: 1,
  CampaignStatus: 'Draft' // added!
}
```

**Comment by ppodolak** [comment]
@michaelrambeau Sorry my bad, the param should be named `Status` not  ` CampaignStatus`. Hope that helps!

**Comment by michaelrambeau** [comment]
@ppodolak It works, thank you very much Pawel!

Closing the issue but let me know if I could to any test for you.
